### PR TITLE
Refactoring and Upgrading

### PR DESCRIPTION
**Pull request by chris-zen**
- Rust compiler upgraded to 1.51.0
- Rust edition upgraded to 2018
- Upgrade coremidi-sys, core-foundation and core-foundation-sys
- Moved `struct`s and `impl`s together
- Applied cargo fmt
- Several Clippy fixes
- **Breaks retro-compatibility for notification events**
   - `IOErrorInfo` renamed to `IoErrorInfo`
   - `Notification::IOError` renamed to `Notification::IoError`
- Bumped version to 0.6.0

Please @jasongrlicky @Boddlnagg could you have a look?

### CODE REVIEW

**Comment by Boddlnagg** [comment]
Looks good to me. I only noticed that `OSStatus` is not consistent with the Rust naming conventions (according to which you changed `IO` to `Io`, so it should also be `Os` instead of `OS`) ... but this is directly imported from core_foundation, so I'm not sure if it would be worth renaming it (i.e. reexport with a different name)?

**Comment by chris-zen** [comment]
Thanks @Boddlnagg, I'd rather not to touch anything outside the crate, as I was basically addressing clippy problems.

By the way, is there any chance that you could try to compile `midir` with this branch?

**Comment by Boddlnagg** [comment]
> By the way, is there any chance that you could try to compile midir with this branch?

Unfortunately not, because I also need to resort to the CI setup to test macOS builds for me since I don't have macOS hardware.

However, you could create a temporary PR in the midir repository where you reference some pre-release/Git version of `coremidi` and let that trigger midir's CI.

**Comment by chris-zen** [comment]
@Boddlnagg I can confirm that `midir` compiles and passes the tests with this version:

```
$ cargo build              
   Compiling core-foundation-sys v0.8.2
   Compiling libc v0.2.97
   Compiling coremidi-sys v3.0.1
   Compiling bitflags v1.2.1
   Compiling memalloc v0.1.0
   Compiling core-foundation v0.9.1
   Compiling coremidi v0.6.0 (/Users/.../coremidi)
   Compiling midir v0.7.0 (/Users/.../midir)
    Finished dev [unoptimized + debuginfo] target(s) in 4.13s
```

**Comment by chris-zen** [comment]
Hi @jasongrlicky, I would appreciate if you could try to compile your code and see if there are many broken things. I did some renamings and moved things around. I'd like to release a new version soon.

**Comment by jasongrlicky** [comment]
Hey @chris-zen, will do. I have family in town this week, but I’m sure I will get a spare second to check it out in the next couple days.

**Pull request merged**
